server:
  port: "8080"
  # servlet:
  #   context-path: /v1/payment-solution

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: mailhog
    port: 1025
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          starttls:
            enable: false
      debug: true
    default-encoding: UTF-8 
  main: 
    debug: true

    
logging:
  level:
    root: DEBUG
    cp630oc.paymentsolution: DEBUG
    org.springframework: INFO
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    org.postgresql: ERROR
    org.apache.catalina.core.AprLifecycleListener: ERROR
    org.apache.tomcat.util.compat.Jre18Compat: ERROR
    org.apache.tomcat.util.compat.Jre19Compat: ERROR
    org.apache.tomcat.util.compat.Jre21Compat: ERROR
    org.apache.tomcat.util.compat.Jre22Compat: ERROR