services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    networks:
      - public-network
    volumes: 
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks: 
      - public-network
    restart: always

  db: 
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    networks: 
      - public-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - pg-data:/var/lib/postgresql/data/pgdata 

  payment-solution:
    image: reidlai/cp630-payment-solution:latest
    container_name: cp630-payment-solution
    ports:
      - "8080:8080"
    networks:
      - public-network
    environment:
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_MAIL_HOST: "mailhog"
      SPRING_MAIL_PORT: "1025"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_SCHEMA: "public"
      MODEL_PATH: "/model/lightgbm_fraud_detector.onnx"
      ENCODER_MAPPING_DIR: "/model" 
    volumes:
      - ./model:/model
    depends_on:
      - db
  mageai:
    image: reidlai/cp630-mageai:latest
    container_name: cp630-mageai
    ports: 
      - "6789:6789"
    networks:
      - public-network
    volumes:
      - ./data-processing/default:/home/src/default
      - mageai-data:/home/src/mage_data
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_SCHEMA: "public"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "pXvDu4WNMZyqLbCNbeJB"
      MINIO_SECRET_KEY: "pocMOObTazz4dI1BBUjX18wp9iFHz3Kk7fls0Y0m"
      MINIO_BUCKET: "test"
    
networks:
  public-network:
    driver: bridge

volumes:
  minio-data:
  pg-data:
  mageai-data:
