services:
  appointment:
    image: caap/appointment:0.0.1
    container_name: appointment-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - caap-network

  coverage-eligibility-request:
    image: caap/coverage-eligibility-request:0.0.1
    container_name: coverage-eligibility-request-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - caap-network

networks:
  caap-network:
    driver: bridge