@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()

System_Ext(emailsystem, "Email System", "A system that used to send email")

System_Boundary(paymentsolution, "Payment Solution", "A solution that detects fraud using AI") {
    Component(PaymentRequestRESTController, "Payment Request REST Controller", "A REST controller that used to receive payment request")
    Component(MessageQueueProducder, "Message Queue Producer", "A producer that used to send payment request to message queue")

    ComponentQueue(MessageQueue, "Message Queue", "A message queue that used to store payment request")

    Component(ModelInferenceConsumer, "Model Inference REST Controller", "A REST controller that used to detect fraud")
    Component(FeatureMappingService, "Feature Mapping Service", "A service that used to map payment request to feature")
    ComponentDb(MachineLearningModel, "Machine Learning Model", "A machine learning model that used to detect fraud")

    Component(NotificationRESTController, "Notification REST Controller", "A REST controller that used to notify payment status")
    Component(SMTPRElayService, "SMTP Relay Service", "A service that connect to external SMTP server to send email")

    ComponentDb(PaymentRequestStore, "Payment Request Store", "A database store that used to store Payment Request")
}

Rel(PaymentRequestRESTController, PaymentRequestStore, "Store payment request")

@enduml